name: Trigger Jitpack Build on New Release

on:
  release:
    types:
      - published
      - edited
      - released
      - created

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get release tag
        id: get_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Trigger Jitpack Build
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          JITPACK_BUILD_URL="https://jitpack.io/com/github/Neptune-Development-Group/neptunelib/$TAG/build.log"
          echo "Triggering JitPack build for $TAG"
          curl -I $JITPACK_BUILD_URL
      - name: Notify success
        run: echo "Jitpack build triggered successfully"