name: Publish on GitHub

on: [ pull_request, workflow_dispatch, push ]

env:
  JAVA_VERSION: 21

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: madhead/read-java-properties@latest
        id: tag
        with:
          file: gradle.properties
          property: mod_version
          default: 0.0.1

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Fixing gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish (Github Release)
        uses: Kir-Antipov/mc-publish@v3.3                                   #The specified MC-Publish GitHub Action in the version 3.3
        with:
          github-prerelease: false
          github-token: "${{secrets.GITHUB_TOKEN}}"

          github-generate-changelog: true
          version-type: release

          loaders: fabric
          java: "${{env.JAVA_VERSION}}"

      - name: Trigger Jitpack Build
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          JITPACK_BUILD_URL="https://jitpack.io/com/github/Neptune-Development-Group/neptunelib/$TAG/build.log"
          echo "Triggering JitPack build for $TAG"
          curl -I $JITPACK_BUILD_URL -m 5

      - name: Notify success
        run: echo "Jitpack build triggered successfully"