name: Publish on GitHub

on: [ pull_request, workflow_dispatch, push ]

env:
  JAVA_VERSION: 21

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Fixing gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (Github Release)
        uses: Kir-Antipov/mc-publish@v3.3                                   #The specified MC-Publish GitHub Action in the version 3.3
        with:
          github-prerelease: false
          github-token: "${{secrets.GITHUB_TOKEN}}"

          github-generate-changelog: true
          version-type: release

          loaders: fabric
          java: "${{env.JAVA_VERSION}}"