name: Publish on GitHub

on: [ pull_request, workflow_dispatch, push ]

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (Github Release)
        if: github.ref = "refs/head/master"
        uses: Kir-Antipov/mc-publish@v3.2                                   #The specified MC-Publish GitHub Action in the version 3.2
        with:
          github-prerelease: false
          github-token: "${{secrets.GITHUB_TOKEN}}"

          github-generate-changelog: true
          version-type: release

          loaders: fabric
          java: "${{env.JAVA_VERSION}}"
      - name: Determine release version
        id: release_version
        run: |
          echo "::set-output name=version::$(if [ '${{ github.ref }}' == 'refs/heads/main' ]; then echo ${{ steps.get_tags.outputs.version }}; else echo 'prerelease-'${{ steps.get_tags.outputs.version }}; fi)"
      - name: Update gradle.properties for not release
        run: |
          sed -i "s/^mod_version=.*/mod_version=${{ steps.release_version.outputs.version }}/" gradle.properties
      - name: Publish (Github Pre-Release)
        if: github.ref != "refs/head/master"
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-prerelease: true
          github-token: "${{secrets.GITHUB_TOKEN}}"

          github-generate-changelog: true
          version-type: beta

          loaders: fabric
          java: "${{env.JAVA_VERSION}}"